package msgs

//TODO sperate the messages for users and ditto for console.
/*const (
	NoJustATrick       = ":eyes: No prank!"
	NoStarter          = "There's no starter"
	NotEnoughMinerals  = ":x::moneybag: Not enough parameters."
	SoEnoughMinerals   = ":moneybag::moneybag::moneybag: So enough parameters. :moneybag::moneybag::moneybag:"
	NoSuchCommand      = ":eyes: No such command."
	Nil                = "is nil."
	AcessUndefinedEnv  = "acessing undefined env"
	NoString           = "interface is not a string"
	UndefinedType      = "undefined type"
	ConvertingError    = "converting error!"
	NotMatchedParms    = "the number of parmeters don't match."
	NoSupportOther     = "currently only supports for string, string slic, int, range and bool."
	PermissionNoString = "permission env is not a string"
)*/
const (
	NoJustATrick       = ":gorani: 장난 노노!"
	NoStarter          = "There's no starter"
	NotEnoughMinerals  = ":x::moneybag: 매개 변수가 부족합니다. "
	SoEnoughMinerals   = ":moneybag::moneybag::moneybag: 매개변수가 풍족합니다. :moneybag::moneybag::moneybag:"
	NoSuchCommand      = ":eyes: 그런거 없어요. "
	Nil                = "is nil."
	AcessUndefinedEnv  = ":eyes: 그런 설정 없어요."
	NoString           = "interface is not a string"
	UndefinedType      = "undefined type"
	TypesDontMatch     = ":eyes: 올바른 형식이 아닌데요"
	NotMatchedParms    = "the number of parmeters don't match."
	NoSupportOther     = "currently only supports for string, string slic, int, range and bool."
	PermissionNoString = "permission env is not a string"
	NoPermission       = ":gorani: 권력이 부족합니다"
	NoID               = ":eyes: 그런 동영상은 없는데요"
	OutOfRange         = ":eyes: 범위에 벗어나는데요"
	NoQueue            = ":question: 노래가 없는데 왜 재생하란거죠"
	HentaiChannel      = ":eyes: 여기서 뭐하시는 겁니까?"
	WhyDisconnect      = ":eyes: 나갈 채널이 없는데 뭐하잔거죠."
	NoCategory         = ":eyes: 그런 카테고리 없어요"
)
