FROM golang:stretch

RUN apt-get update && apt-get install -y \ 
            ffmpeg \
            curl
RUN curl -o /usr/bin/youtube-dl http://yt-dl.org/latest/youtube-dl
RUN chmod 755 /usr/bin/youtube-dl
    
